.PHONY: help

help:
	@echo "Available targets:"
	@echo "  make env-check"
	@echo "  make db-start"
	@echo "  make db-shell"
	@echo "  make seed-state SEED_PRESET=loadtest"
	@echo "  make grafana-generate"
	@echo "  make phase-sql FILE=scripts/phase-06/12-review-naive-prepare.sql"
	@echo "  make phase-sql FILE=scripts/phase-06/13-review-naive-explain.sql OUTPUT=docs/evidence/phase-06/review-aggregate/naive-index/explain.txt"
	@echo "  make k6-evidence PHASE=phase-06 SCENARIO=review-summary PRESET=review-summary-baseline CONDITION=naive-index"
	@echo "  make grafana-capture PHASE=phase-06 SCENARIO=review-summary PRESET=baseline TABLE=review"
	@echo "  make evidence-capture PHASE=phase-06 SCENARIO=review-summary PRESET=review-summary-baseline CONDITION=query-shaped-index TABLE=review"
	@echo "  make phase-status PHASE=phase-06"
	@echo ""
	@echo "Common required variables:"
	@echo "  seed-state: SEED_PRESET"
	@echo "  phase-sql: FILE, optional OUTPUT"
	@echo "  k6-evidence/evidence-capture: PHASE, SCENARIO, CONDITION, PRESET or K6_PRESET"
	@echo "  grafana-capture: PHASE, SCENARIO, PRESET or GRAFANA_PRESET, optional WINDOW_FILE"
	@echo ""
	@echo "Preset variables:"
	@echo "  PRESET: public preset for k6 and Grafana"
	@echo "  K6_PRESET: k6 preset override, defaults to PRESET"
	@echo "  GRAFANA_PRESET: Grafana preset variable override, defaults to PRESET"
	@echo ""
	@echo "Default output roots:"
	@echo "  SQL/k6 evidence: docs/evidence/<phase>/"
	@echo "  Grafana screenshots: docs/evidence/<phase>/grafana-screenshots/"
