.PHONY: help

help:
	@echo "Available targets:"
	@echo "  make env-check"
	@echo "  make db-start"
	@echo "  make db-shell"
	@echo "  make grafana-generate"
	@echo "  make phase-sql PHASE=phase-06 SCENARIO=review-aggregate CONDITION=naive-index ACTION=prepare"
	@echo "  make phase-sql PHASE=phase-06 SCENARIO=review-aggregate CONDITION=naive-index ACTION=explain OUTPUT=docs/evidence/phase-06/review-aggregate/naive-index/explain.txt"
	@echo "  make k6-evidence PHASE=phase-06 SCENARIO=review-summary CONDITION=naive-index"
	@echo "  make grafana-capture PHASE=phase-06 SCENARIO=review-summary CONDITION=naive-index TABLE=review"
	@echo "  make evidence-capture PHASE=phase-06 SCENARIO=review-summary CONDITION=query-shaped-index TABLE=review"
	@echo "  make phase-status PHASE=phase-06"
	@echo ""
	@echo "Common required variables:"
	@echo "  phase-sql: PHASE, SCENARIO, ACTION, and CONDITION for aggregation scenarios"
	@echo "  k6-evidence/evidence-capture: PHASE, SCENARIO, CONDITION"
	@echo "  grafana-capture: PHASE, SCENARIO, optional WINDOW_FILE for fixed evidence captures"
	@echo ""
	@echo "Preset variables:"
	@echo "  PRESET: public default for k6 and Grafana"
	@echo "  K6_PRESET: k6 preset override, defaults to PRESET"
	@echo "  GRAFANA_PRESET: Grafana preset variable override, defaults to PRESET"
	@echo ""
	@echo "Default output roots:"
	@echo "  SQL/k6 evidence: docs/evidence/<phase>/"
	@echo "  Grafana screenshots: docs/evidence/<phase>/grafana-screenshots/"
